### ISSUE TITLE
Stacktach installed, consuming messages but web interface shows "no results"

### ISSUE THREAD

**Issue by cousins** [rackerlabs/stacktach#347]
Hi Sandy,

I met you at the OPS meeting in Philly (one of the guys from Maine) and I finally installed Stacktach v2 to see if I could do anything with the 200,000+ messages queued in notifications.info. It seems to be consuming the messages (now down 170,000 before I stopped the worker) and I can see a lot of entries in the stacktach_instanceexists table (so far 41806). They all seem to have a status of "pending".

Anyway, when I look at 127.0.0.1:8000 I get the StackTach page and see the deployment I created but clicking on it just shows 

    deployment source tenant service host event instance when

"No results" 

and in the Commands section I can't get it to show anything no matter what I click on or search for.

I have tried the github and stackforge versions. 

Maybe I should just keep the worker going to get all messages but I wanted to check first to see if there is something wrong. I didn't want to consume all of the messages only to find that it wasn't getting all of the information.

Any recommendations on things to check?

Thanks a lot,

Steve

**Comment by SandyWalsh** [comment]
Hey Steve!

Glad to hear you got things going. Getting notifications generated and consumed is the hardest part. You should use the stackforge repo, that's the latest (I need to get the old ones killed off).

The UI will only show the latest notifications, so I suspect it's consuming the oldest events first and there's nothing "recent" to show. 

If you use the stacky cmdline tool [1] or the gui search command you should get results. 

If you still have problems, let me know!

[1] https://github.com/rackerlabs/stacky
